-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 22:11:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Chairman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chairman` (
  `ChairmanID` INT NOT NULL,
  `ChairmanName` VARCHAR(45) NULL,
  `ChairmanEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`ChairmanID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `DepartmentCode` INT NOT NULL,
  `DepartmentName` VARCHAR(45) NULL,
  `DepartmentEmail` VARCHAR(45) NULL,
  `College` VARCHAR(45) NULL,
  `Chairman_ChairmanID` INT NOT NULL,
  PRIMARY KEY (`DepartmentCode`),
  INDEX `fk_Department_Chairman1_idx` (`Chairman_ChairmanID` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Chairman1`
    FOREIGN KEY (`Chairman_ChairmanID`)
    REFERENCES `mydb`.`Chairman` (`ChairmanID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `StudentID` INT NOT NULL,
  `StudentName` VARCHAR(45) NULL,
  `StudentEmail` VARCHAR(45) NULL,
  `StudentMajor` VARCHAR(45) NULL,
  `Department_DepartmentCode` INT NOT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `fk_Student_Department1_idx` (`Department_DepartmentCode` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Department1`
    FOREIGN KEY (`Department_DepartmentCode`)
    REFERENCES `mydb`.`Department` (`DepartmentCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Section` (
  `SectionNumber` INT NOT NULL,
  PRIMARY KEY (`SectionNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_has_Section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_has_Section` (
  `Student_StudentID` INT NOT NULL,
  `Section_SectionNumber` INT NOT NULL,
  PRIMARY KEY (`Student_StudentID`, `Section_SectionNumber`),
  INDEX `fk_Student_has_Section_Section1_idx` (`Section_SectionNumber` ASC) VISIBLE,
  INDEX `fk_Student_has_Section_Student_idx` (`Student_StudentID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Section_Student`
    FOREIGN KEY (`Student_StudentID`)
    REFERENCES `mydb`.`Student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Section_Section1`
    FOREIGN KEY (`Section_SectionNumber`)
    REFERENCES `mydb`.`Section` (`SectionNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
